image: alpine

stages:
  - build
  - deploy

pages:
  stage: deploy
  script:
    # Créer un répertoire public et copier tous les fichiers dedans
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
