name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Cloner le code du dépôt GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Installer Docker et configurer Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 3. Se connecter à Docker Hub avec ton nom d'utilisateur
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Construire l'image Docker avec le bon nom (utilise benjibrana comme utilisateur)
    - name: Build Docker image
      run: docker build -t benjibrana/ci_cd:latest .

    # 5. Pousser l'image vers Docker Hub
    - name: Push Docker image
      run: docker push benjibrana/ci_cd:latest
